# Generated by Django 4.1.7 on 2023-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('producator', models.CharField(max_length=50)),
                ('pret', models.FloatField(blank=True, null=True)),
                ('necesita_reteta', models.BooleanField(default=False)),
            ],
        ),
    ]
