# Generated by Django 4.1.7 on 2023-03-04 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FarmacieOnline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'ordering': ['-nume']},
        ),
        migrations.CreateModel(
            name='Tranzactie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numar_bucati', models.IntegerField()),
                ('data_tranzactie', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmacieOnline.medicament')),
            ],
        ),
    ]
